// PDF guide files used by the summary table and factor detail drawer.
window.FACTOR_EXPLAIN = {};
window.FACTOR_GUIDES = window.FACTOR_GUIDES || {
  5: 'guides/01_Earthquake_Fault_Lines.pdf',
  6: 'guides/02_Soil_Liquefaction_Zones.pdf',
  7: 'guides/03_Landslide_Zones.pdf',
  8: 'guides/04_FEMA_Flood_Zone.pdf',
  9: 'guides/05_Dams_Inundation.pdf',
  10: 'guides/06_Rivers_Streams_Creeks.pdf',
  11: 'guides/07_Fire_Hazard_Severity_Zone.pdf',
  13: 'guides/08_Oil_Gas_Hazard_Pipelines.pdf',
  14: 'guides/09_Oil_Natural_Gas_Wells.pdf',
  15: 'guides/10_Superfund_NPL_Sites.pdf',
  16: 'guides/11_EPA_CalEPA_Regulated_Sites.pdf',
  17: 'guides/12_Mines.pdf',
  19: 'guides/13_Waste_Dump_Sites.pdf',
  20: 'guides/14_Sewage_Wastewater_Treatment.pdf',
  21: 'guides/15_Drinking_Water_Contamination.pdf',
  22: 'guides/16_Ground_Water_Collection.pdf',
  23: 'guides/17_Pesticide_Use.pdf',
  24: 'guides/18_Gas_Stations.pdf',
  25: 'guides/19_Microwave_Stations.pdf',
  26: 'guides/20_Cell_Towers.pdf',
  27: 'guides/21_Air_Pollution_PM2_5.pdf',
  28: 'guides/22_Overall_Pollution.pdf',
  29: 'guides/23_Traffic_Density.pdf',
  30: 'guides/24_Rail_Tracks.pdf',
  31: 'guides/25_Powerline.pdf',
  32: 'guides/26_Noise_Level.pdf',
  33: 'guides/27_Airports_Overflight.pdf',
  48: 'guides/28_Meat_Processing_Plant.pdf',
};
