/* 36 risk/livability factors for any California address.
   Map-link placeholders: {ADDR}(URL-enc), {LAT}, {LON}, {LONABS}, {ZIP}, {CITY}.
   recenter: 'coords' | 'addr' | 'search'   live: API key or null
   detail : what this factor is / what the live map shows.
   impact : how the factor affects each dimension — { level, why }
            level ∈ 'NA' | 'No' | 'Low' | 'Moderate' | 'High'  (drives color + score band)
   Impacts describe the factor's *potential* effect (generic to any address);
   live lookups (e.g. FEMA flood) override the relevant level with the real result. */
const G = "https://www.google.com/maps/search/?api=1&query={ADDR}";

const FACTORS = [
 {n:1, cat:"About / Demographics", name:"Address & ZIP Profile",
  map:"https://www.zip-codes.com/zip-code/{ZIP}/zip-code-{ZIP}.asp", recenter:'addr', live:'census', basemap:'street',
  detail:"Population, median household income, median home value and education level for the ZIP — the socioeconomic backdrop for the address.",
  impact:{health:{level:'NA',why:"Demographic context, not a health hazard."},
          property:{level:'No',why:"Wealth/education context supports value; not itself a risk."},
          insurance:{level:'NA',why:"Not an insurance-pricing factor."}}},

 {n:2, cat:"Schools", name:"School Zones & Ratings",
  map:"https://www.greatschools.org/school-district-boundaries-map/?lat={LAT}&lon={LON}", recenter:'coords', live:'osm', basemap:'street', alt:"https://www.google.com/maps/search/?api=1&query=schools%20near%20{ADDR}",
  detail:"Live OpenStreetMap school-access check near the address; use GreatSchools or the district for assigned-school ratings.",
  impact:{health:{level:'NA',why:"No direct health effect."},
          property:{level:'Moderate',why:"School quality is a strong driver of home values."},
          insurance:{level:'NA',why:"Not used in insurance pricing."}}},

 {n:3, cat:"Crime", name:"Crime & Public Safety",
  map:"https://www.crimemapping.com/", recenter:'search', live:null, basemap:'street', alt:"https://communitycrimemap.com/?address={ADDR}",
  detail:"Recent reported violent and property incidents around the address versus city/national norms.",
  impact:{health:{level:'Low',why:"Higher crime raises personal-safety and stress risk."},
          property:{level:'Moderate',why:"Crime levels strongly influence buyer demand and value."},
          insurance:{level:'Low',why:"Theft/vandalism rates modestly affect premiums."}}},

 {n:4, cat:"Zoning", name:"Zoning / Land Use",
  map:G, recenter:'addr', live:null, basemap:'street',
  detail:"Residential / commercial / mixed-use designation and neighboring land uses.",
  impact:{health:{level:'NA',why:"No direct health hazard."},
          property:{level:'Low',why:"Incompatible adjacent uses can reduce value."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},

 {n:5, cat:"Earthquake", name:"Earthquake Fault Lines",
  map:"https://maps.conservation.ca.gov/cgs/fam/?location={LAT},{LON},14", recenter:'coords', live:null, basemap:'topo',
  detail:"Proximity to active / potentially-active faults and Alquist-Priolo zones.",
  impact:{health:{level:'NA',why:"Not a chronic health exposure."},
          property:{level:'High',why:"Severe shaking can cause major structural damage."},
          insurance:{level:'High',why:"Earthquake coverage is separate and expensive."}}},

 {n:6, cat:"Earthquake", name:"Soil Liquefaction Zones",
  map:"https://maps.conservation.ca.gov/cgs/informationwarehouse/eqzapp/", recenter:'search', live:null, basemap:'topo',
  detail:"CGS seismic-hazard zones where saturated soils may liquefy in a quake.",
  impact:{health:{level:'NA',why:"No direct health exposure."},
          property:{level:'Moderate',why:"Liquefiable soils can crack foundations in a quake."},
          insurance:{level:'Moderate',why:"Adds to earthquake / structural insurance cost."}}},

 {n:7, cat:"Earthquake", name:"Landslide Zones",
  map:"https://gis.data.ca.gov/datasets/cadoc::cgs-seismic-hazards-program-landslide-zones/explore?location={LAT}%2C{LON}%2C13.00", recenter:'coords', live:null, basemap:'topo',
  detail:"CGS earthquake-induced landslide zones on steeper slopes.",
  impact:{health:{level:'NA',why:"No direct health exposure."},
          property:{level:'Moderate',why:"Slope failure can damage hillside structures."},
          insurance:{level:'Moderate',why:"Earth-movement is often excluded or costly to cover."}}},

 {n:8, cat:"Flood", name:"FEMA Flood Zone",
  map:"https://hazards-fema.maps.arcgis.com/apps/webappviewer/index.html?id=5852ea902db44e55bfce395799315f9c&find={ADDR}", recenter:'addr', live:'fema', basemap:'imagery', alt:"https://msc.fema.gov/portal/search?AddressQuery={ADDR}",
  detail:"FEMA flood zone at the exact point. SFHAs (A/AE/V) require flood insurance; Zone X is minimal.",
  impact:{health:{level:'NA',why:"No chronic health exposure."},
          property:{level:'Low',why:"A flood-zone location lowers value and resale."},
          insurance:{level:'Low',why:"An SFHA triggers mandatory flood insurance."}}},

 {n:9, cat:"Flood", name:"Dams & Inundation",
  map:"https://fmds.water.ca.gov/webgis/?appid=dam_prototype_v2", recenter:'search', live:null, basemap:'topo',
  detail:"Whether the address lies in a downstream dam-failure inundation pathway.",
  impact:{health:{level:'NA',why:"No direct health exposure."},
          property:{level:'Low',why:"Inundation-zone location can deter buyers."},
          insurance:{level:'Low',why:"May affect the need for flood coverage."}}},

 {n:10, cat:"Flood", name:"Rivers, Streams, Creeks",
  map:"https://www.arcgis.com/apps/mapviewer/index.html?layers=f078eaa6e4b542eb8877d396127e95c1&center={LON},{LAT}&level=14", recenter:'coords', live:null, basemap:'topo',
  detail:"Nearby watercourses; creek-adjacent parcels carry erosion and localized flood exposure.",
  impact:{health:{level:'NA',why:"No direct health exposure."},
          property:{level:'Low',why:"Creek-adjacency adds erosion and flood concern."},
          insurance:{level:'Moderate',why:"Near-water parcels face higher flood premiums."}}},

 {n:11, cat:"Fire", name:"Fire Hazard Severity Zone",
  map:"https://experience.arcgis.com/experience/5065c998b4b0462f9ec3c6c226c610a9/", recenter:'search', live:null, basemap:'imagery', alt:"https://egis.fire.ca.gov/FHSZ/",
  detail:"CAL FIRE Fire Hazard Severity Zone (Moderate / High / Very High).",
  impact:{health:{level:'Low',why:"Wildfire smoke episodes can affect respiratory health."},
          property:{level:'Moderate',why:"Wildland-interface parcels risk fire loss."},
          insurance:{level:'High',why:"High-hazard zones drive costly or non-renewed coverage."}}},

 {n:12, cat:"Fire", name:"Fire Station Coverage",
  map:"https://www.google.com/maps/search/?api=1&query=fire%20station%20near%20{ADDR}", recenter:'addr', live:null, basemap:'street',
  detail:"Nearest fire stations and response distance.",
  impact:{health:{level:'NA',why:"No direct health effect."},
          property:{level:'No',why:"Good coverage is a positive, not a risk."},
          insurance:{level:'Low',why:"Closer stations can lower ISO-based premiums."}}},

 {n:13, cat:"Oil & Gas", name:"Oil, Gas & Hazard Pipelines",
  map:"https://pvnpms.phmsa.dot.gov/PublicViewer/", recenter:'search', live:null, basemap:'topo',
  detail:"PHMSA gas-transmission and hazardous-liquid pipelines (NPMS Public Viewer shows one county at a time — select your state and county, per the note when an address is analyzed).",
  impact:{health:{level:'Low',why:"Rupture risk for parcels near a transmission easement."},
          property:{level:'Low',why:"Easement proximity can deter some buyers."},
          insurance:{level:'Moderate',why:"Premiums can rise for parcels near a line."}}},

 {n:14, cat:"Oil & Gas", name:"Oil & Natural Gas Wells",
  map:"https://maps.conservation.ca.gov/doggr/wellfinder/", recenter:'search', live:null, basemap:'topo',
  detail:"CalGEM active / idle / plugged wells nearby.",
  impact:{health:{level:'Low',why:"Active wells may emit; plugged wells are minimal."},
          property:{level:'Low',why:"Nearby wells can affect desirability."},
          insurance:{level:'Low',why:"Minor unless an active well is adjacent."}}},

 {n:15, cat:"Superfund & Brownfield", name:"Superfund (NPL) Sites",
  map:"https://epa.maps.arcgis.com/apps/webappviewer/index.html?id=33cebcdfdd1b4c3a8b51d416956c41f1&find={ADDR}", recenter:'addr', live:'epa', basemap:'gray',
  alt:"https://epa.maps.arcgis.com/apps/webappviewer/index.html?id=33cebcdfdd1b4c3a8b51d416956c41f1&find={ADDR}",
  detail:"Live EPA National Priorities List boundary check within 1, 5, and 10 miles of the address.",
  impact:{health:{level:'High',why:"Serious exposure risk if a site is nearby."},
          property:{level:'High',why:"Adjacent contamination sharply cuts value."},
          insurance:{level:'NA',why:"Not a standard property-insurance factor."}}},

 {n:16, cat:"Superfund & Brownfield", name:"EPA / CalEPA Regulated Sites",
  map:"https://siteportal.calepa.ca.gov/nsite/map/help", recenter:'search', live:null, basemap:'gray',
  detail:"Permitted, regulated and cleanup-program facilities near the address.",
  impact:{health:{level:'Low',why:"Most are routine; active cleanup cases matter more."},
          property:{level:'Low',why:"Nearby cleanup cases can weigh on value."},
          insurance:{level:'NA',why:"Not a standard insurance factor."}}},

 {n:17, cat:"Mines", name:"Mines",
  map:"https://maps.conservation.ca.gov/mol/index.html", recenter:'search', live:null, basemap:'topo',
  detail:"Active and historic mine locations.",
  impact:{health:{level:'Low',why:"Legacy mines can carry contamination or gas."},
          property:{level:'Low',why:"Subsidence risk can affect nearby parcels."},
          insurance:{level:'NA',why:"Not a standard insurance factor."}}},

 {n:18, cat:"Mines", name:"Mines & Fault-Line Overlap",
  map:"https://maps.conservation.ca.gov/mol/index.html", recenter:'search', live:null, basemap:'topo',
  detail:"Mine sites coincident with fault zones — a compound stability concern.",
  impact:{health:{level:'Low',why:"Compound subsidence/seismic concern if present."},
          property:{level:'Low',why:"Combined hazard can affect value where present."},
          insurance:{level:'NA',why:"Not a standard insurance factor."}}},

 {n:19, cat:"Dump Sites", name:"Waste / Dump Sites",
  map:"https://oehha.maps.arcgis.com/apps/instant/sidebar/index.html?appid=32262911130441d68d0521ec10b429a5&center={LON},{LAT}&level=13", recenter:'coords', live:null, basemap:'gray',
  detail:"Landfills and solid-waste disposal sites near the address.",
  impact:{health:{level:'Low',why:"Odor, vectors or legacy gas if very close."},
          property:{level:'Low',why:"Proximity can lower desirability."},
          insurance:{level:'NA',why:"Not a standard insurance factor."}}},

 {n:20, cat:"Sewage", name:"Sewage / Wastewater Treatment",
  map:"https://www.waterandwastewater.com/us-wastewater-treatment-plants-map/", recenter:'search', live:null, basemap:'gray',
  detail:"Proximity to wastewater treatment plants.",
  impact:{health:{level:'Low',why:"Odor/nuisance only if immediately adjacent."},
          property:{level:'Low',why:"Adjacent plants can reduce desirability."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},

 {n:21, cat:"Drinking Water", name:"Drinking Water Standard",
  map:"https://wdl.water.ca.gov/waterdatalibrary/Map.aspx", recenter:'search', live:null, basemap:'gray',
  detail:"Serving water system and its compliance with drinking-water standards.",
  impact:{health:{level:'Moderate',why:"Water quality directly affects health."},
          property:{level:'Low',why:"Persistent violations can weigh on value."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},

 {n:22, cat:"Drinking Water", name:"Ground Water Collection",
  map:"https://wdl.water.ca.gov/waterdatalibrary/Map.aspx", recenter:'search', live:null, basemap:'gray',
  detail:"Whether supply relies on local groundwater wells/basins vs. treated surface water.",
  impact:{health:{level:'Low',why:"Local well reliance can affect water quality."},
          property:{level:'Low',why:"Basin dependence can matter in droughts."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},

 {n:23, cat:"Chemical Pollution", name:"Pesticide Use",
  map:"https://trackingcalifornia.org/data-and-tools/pesticide-mapping-tool#gsc.tab=0", recenter:'search', live:null, basemap:'topo',
  detail:"Agricultural pesticide application intensity in the surrounding area.",
  impact:{health:{level:'Moderate',why:"Heavy nearby application raises exposure."},
          property:{level:'Low',why:"Ag-adjacency can deter some buyers."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},

 {n:24, cat:"Chemical Pollution", name:"Gas Stations",
  map:"https://www.arcgis.com/apps/mapviewer/index.html?layers=ec575b2693f64199866bc18744d232fe&center={LON},{LAT}&level=14", recenter:'coords', live:null, basemap:'street',
  detail:"Retail fuel and underground storage tanks nearby.",
  impact:{health:{level:'Low',why:"UST leaks/vapors risk for adjacent parcels."},
          property:{level:'Low',why:"Adjacency can reduce desirability."},
          insurance:{level:'NA',why:"Not a standard insurance factor."}}},

 {n:25, cat:"Microwave & Cell", name:"Microwave Stations",
  map:"https://www.antennasearch.com/HTML/search/search.php?address={ADDR}", recenter:'addr', live:null, basemap:'topo',
  detail:"Fixed point-to-point microwave links registered near the address.",
  impact:{health:{level:'Low',why:"Directional links; minimal public exposure."},
          property:{level:'Low',why:"Minor visual/proximity preference effect."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},

 {n:26, cat:"Microwave & Cell", name:"Cell Towers",
  map:"https://www.antennasearch.com/HTML/search/search.php?address={ADDR}", recenter:'addr', live:null, basemap:'street',
  detail:"FCC-registered towers and antennas nearby.",
  impact:{health:{level:'Low',why:"RF is typically far below public limits."},
          property:{level:'Low',why:"View/proximity can affect some buyers."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},

 {n:27, cat:"Overall Pollution", name:"Air Pollution (PM2.5)",
  map:"https://www.baaqmd.gov/en/about-air-quality/interactive-data-maps", recenter:'search', live:null, basemap:'gray', alt:"https://map.purpleair.com/1/mAQI/a10/p604800/cC0#13/{LAT}/{LON}",
  detail:"Fine-particulate air quality near the address, including wildfire-smoke episodes.",
  impact:{health:{level:'Moderate',why:"Particulates affect respiratory and cardiac health."},
          property:{level:'Low',why:"Poor air quality can soften demand."},
          insurance:{level:'NA',why:"Not a standard insurance factor."}}},

 {n:28, cat:"Overall Pollution", name:"Overall Pollution (CalEnviroScreen)",
  map:"https://experience.arcgis.com/experience/ed5953d89038431dbf4f22ab9abfe40d/", recenter:'search', live:null, basemap:'gray',
  detail:"Cumulative environmental pollution-burden percentile from CalEnviroScreen.",
  impact:{health:{level:'Moderate',why:"Cumulative burden affects long-term health."},
          property:{level:'Low',why:"High-burden areas can see lower demand."},
          insurance:{level:'NA',why:"Not a standard insurance factor."}}},

 {n:29, cat:"Overall Pollution", name:"Highway Traffic Pollution",
  map:"https://ext.trackingcalifornia.org/traffic/#/map/explore", recenter:'search', live:null, basemap:'street',
  detail:"Near-roadway / freeway-corridor air and noise exposure.",
  impact:{health:{level:'Moderate',why:"Near-freeway air/noise harms health within ~500 ft."},
          property:{level:'Low',why:"Freeway adjacency can lower value."},
          insurance:{level:'NA',why:"Not a standard insurance factor."}}},

 {n:30, cat:"Freight Rail", name:"Freight Rail Tracks",
  map:"https://www.arcgis.com/apps/webappviewer/index.html?id=010cb07a67a4437f9db5e72090adb0dc&find={ADDR}", recenter:'addr', live:null, basemap:'street',
  detail:"Active freight rail corridors near the address.",
  impact:{health:{level:'Low',why:"Noise/vibration and crossing hazards nearby."},
          property:{level:'Low',why:"Track adjacency can reduce value."},
          insurance:{level:'NA',why:"Not a standard insurance factor."}}},

 {n:31, cat:"Power Transmission", name:"High-Voltage Power Lines",
  map:"https://felt.com/map/US-Electric-Power-Transmission-Lines-in-the-city-of-San-Francisco-California-owyaIpVBTVONQwcJ9ALn9CqB?loc={LAT},{LON},13z", recenter:'coords', live:null, basemap:'topo',
  detail:"High-voltage transmission corridors; ELF-EMF falls off quickly with distance.",
  impact:{health:{level:'Low',why:"ELF-EMF drops quickly with distance from lines."},
          property:{level:'Low',why:"Under/adjacent-to-line parcels are less desirable."},
          insurance:{level:'NA',why:"Not a standard insurance factor."}}},

 {n:32, cat:"Noise", name:"Noise Level",
  map:"https://experience.arcgis.com/experience/ca7be47121e24f2bb8f5e3017051d402/", recenter:'search', live:null, basemap:'street',
  detail:"Modeled transportation noise (road, rail, aviation) at the address.",
  impact:{health:{level:'Low',why:"Chronic noise affects sleep and stress."},
          property:{level:'Moderate',why:"Noise materially affects desirability and value."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},

 {n:33, cat:"Facilities", name:"Airports & Overflight",
  map:"https://gis.data.ca.gov/datasets/082f0a402b354e53a7df995de3317fe2_0/explore?location={LAT}%2C{LON}%2C11", recenter:'coords', live:null, basemap:'imagery',
  detail:"Airport proximity and approach-path overflight, plus access convenience.",
  impact:{health:{level:'Low',why:"Overflight noise under approach paths."},
          property:{level:'Moderate',why:"Flight-path parcels can see lower value."},
          insurance:{level:'NA',why:"Not a standard insurance factor."}}},

 {n:34, cat:"Facilities", name:"BART / Transit Access",
  map:"https://www.google.com/maps/search/?api=1&query=transit%20station%20near%20{ADDR}", recenter:'addr', live:null, basemap:'street',
  detail:"Rail/BART and transit accessibility — a convenience and value positive.",
  impact:{health:{level:'NA',why:"No health hazard."},
          property:{level:'No',why:"Transit access is a value positive."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},

 {n:35, cat:"Facilities", name:"Park & Ride",
  map:"https://www.google.com/maps/search/?api=1&query=park%20and%20ride%20near%20{ADDR}", recenter:'addr', live:null, basemap:'street',
  detail:"Nearby commuter park-and-ride lots supporting the commute.",
  impact:{health:{level:'NA',why:"No health hazard."},
          property:{level:'No',why:"Commute convenience is a minor positive."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},

 {n:36, cat:"Cemeteries", name:"Cemeteries",
  map:"https://www.google.com/maps/search/?api=1&query=cemetery%20near%20{ADDR}", recenter:'addr', live:null, basemap:'street',
  detail:"Cemetery proximity (a buyer-preference factor for some).",
  impact:{health:{level:'NA',why:"No health effect."},
          property:{level:'Low',why:"A buyer-preference factor for some."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},,

 /* ---------- Livability & lifestyle (live-scored via OpenStreetMap/Census) ---------- */
 {n:37, cat:"Livability", name:"Colleges & Universities",
  map:"https://www.google.com/maps/search/?api=1&query=colleges%20universities%20near%20{ADDR}", recenter:'addr', live:'osm', basemap:'street',
  detail:"Higher-education campuses near the address (checked live via OpenStreetMap).",
  impact:{health:{level:'NA',why:"No health effect."},
          property:{level:'Low',why:"Campus proximity supports rental demand and values."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},

 {n:38, cat:"Livability", name:"Restaurants & Retail",
  map:"https://www.google.com/maps/search/?api=1&query=restaurants%20near%20{ADDR}", recenter:'addr', live:'osm', basemap:'street',
  detail:"Dining and shopping density within about a mile (live OpenStreetMap count).",
  impact:{health:{level:'NA',why:"No direct health effect."},
          property:{level:'Low',why:"Amenity-rich areas hold value better."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},

 {n:39, cat:"Livability", name:"Parks & Recreation",
  map:"https://www.google.com/maps/search/?api=1&query=parks%20near%20{ADDR}", recenter:'addr', live:'osm', basemap:'street',
  detail:"Parks, playgrounds and green space within about a mile (live OpenStreetMap count).",
  impact:{health:{level:'Low',why:"Green-space access supports physical & mental health."},
          property:{level:'Low',why:"Park proximity is a value positive."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},

 {n:40, cat:"Livability", name:"Walkability & Transit",
  map:"https://www.google.com/maps/search/?api=1&query=transit%20near%20{ADDR}", recenter:'addr', live:'osm', basemap:'street',
  detail:"Transit stops and everyday destinations within walking range (live OpenStreetMap count).",
  impact:{health:{level:'Low',why:"Walkable areas encourage active lifestyles."},
          property:{level:'Low',why:"Walkability commands a price premium."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},

 {n:41, cat:"Livability", name:"Commute & Accessibility",
  map:"https://www.google.com/maps/search/?api=1&query=freeway%20entrance%20near%20{ADDR}", recenter:'addr', live:'osm', basemap:'street',
  detail:"Freeway access and rail stations within reach (live OpenStreetMap check).",
  impact:{health:{level:'NA',why:"No direct health effect."},
          property:{level:'Low',why:"Poor access can weigh on resale."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},

 {n:42, cat:"Livability", name:"Healthcare Access",
  map:"https://www.google.com/maps/search/?api=1&query=hospital%20clinic%20near%20{ADDR}", recenter:'addr', live:'osm', basemap:'street',
  detail:"Hospitals, clinics and pharmacies near the address (live OpenStreetMap count).",
  impact:{health:{level:'Moderate',why:"Distance to care matters in emergencies."},
          property:{level:'Low',why:"Healthcare access is a modest value factor."},
          insurance:{level:'NA',why:"Not a standard property-insurance factor."}}},

 {n:43, cat:"Livability", name:"Property Value (ACS)",
  map:"https://www.zillow.com/homes/{ZIP}_rb/", recenter:'addr', live:'census', basemap:'street',
  detail:"ZIP median home value from the U.S. Census ACS; open Zillow for market trends.",
  impact:{health:{level:'NA',why:"Not a health factor."},
          property:{level:'No',why:"Context metric for the local market."},
          insurance:{level:'Low',why:"Higher values raise replacement-cost premiums."}}},

 {n:44, cat:"Livability", name:"Community & Lifestyle Fit",
  map:"https://www.google.com/maps/search/?api=1&query=library%20community%20center%20near%20{ADDR}", recenter:'addr', live:'osm', basemap:'street',
  detail:"Libraries, community centers and gathering places nearby (live OpenStreetMap count) — an indicative community-infrastructure signal.",
  impact:{health:{level:'Low',why:"Social infrastructure supports wellbeing."},
          property:{level:'Low',why:"Community amenities support desirability."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},

 {n:45, cat:"Livability", name:"Future Development Activity",
  map:"https://www.google.com/maps/search/?api=1&query=construction%20near%20{ADDR}", recenter:'addr', live:'osm', basemap:'street',
  detail:"Mapped construction activity near the address (live OpenStreetMap proxy) — growth signal, but also change/noise; check the city planning page for entitled projects.",
  impact:{health:{level:'NA',why:"No direct health effect."},
          property:{level:'Low',why:"Development can lift or pressure values depending on type."},
          insurance:{level:'NA',why:"Not an insurance factor."}}},

 {n:46, cat:"Tsunami", name:"Tsunami Evacuation Zone",
  map:"https://maps.conservation.ca.gov/cgs/informationwarehouse/index.html?map=ts_evacuation&location={LAT},{LON},14", recenter:'coords', live:null, basemap:'topo',
  detail:"California Geological Survey tsunami evacuation map for coastal inundation planning; opens zoomed to the searched address.",
  impact:{health:{level:'High',why:"Tsunami zones indicate life-safety evacuation exposure during rare coastal events."},
          property:{level:'Moderate',why:"Mapped coastal evacuation context can affect due diligence and buyer perception."},
          insurance:{level:'Low',why:"Tsunami exposure is generally reviewed through flood / coastal hazard coverage context."}}}
];

if (typeof module !== 'undefined') module.exports = { FACTORS };
